export const FETCH_PARENTS = "FETCH_PARENTS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERRORS = "SET_ERRORS";

export const FETCH_ITEMS = "FETCH_ITEMS";
export const CREATE_ITEM = "CREATE_ITEM";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const FETCH_ITEM_DETAIL = "FETCH_ITEM_DETAIL";

export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
