export const FETCH_ALL_STUDENTS = "FETCH_ALL_STUDENTS";
export const FETCH_DETAIL_STUDENT = "FETCH_DETAIL_STUDENT";
export const STUDENT_ADD = "STUDENT_ADD";
export const STUDENT_UPDATE = "STUDENT_UPDATE";
export const STUDENT_DELETE = "STUDENT_DELETE";
