export const FETCH_ITEMS = "FETCH_ITEMS";

export const FETCH_PARENTS = "FETCH_PARENTS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERRORS = "SET_ERRORS";

export const CREATE_ITEM = "CREATE_ITEM";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";

export const FETCH_CATEGORIES = "FETCH_CATEGORIES";

export const FETCH_SCHOOL_PROFILE = "FETCH_SCHOOL_PROFILE";

export const SET_LOADING = "SET_LOADING";